// <auto-generated />
namespace FreeWheeling.Domain.DataContexts.CycleMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class User_Expand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Expand));
        
        string IMigrationMetadata.Id
        {
            get { return "201402030103074_User_Expand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
