// <auto-generated />
namespace FreeWheeling.Domain.DataContexts.CycleMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class riderequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(riderequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201401191114336_riderequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
